// Copyright 2026 NDC Digital, LLC
// SPDX-License-Identifier: Apache-2.0

package dev.flametrench.identity;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Flametrench v0.1 conformance suite — Java / JUnit 5 harness for the
 * identity capability.
 *
 * <p>Exercises verify_password against the cross-language Argon2id
 * parity fixture vendored from
 * github.com/flametrench/spec/conformance/fixtures/identity/.
 *
 * <p>Why this fixture matters: the fixture's PHC hash was generated by
 * the Node {@code argon2} package. Java's {@code argon2-jvm} (which
 * wraps libargon2) MUST accept it. If this test fails, password-based
 * auth has become non-portable across SDKs — a regression Flametrench
 * exists to prevent.
 */
class ConformanceTest {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private static JsonNode loadFixture(String relativePath) throws IOException {
        String resource = "/conformance/fixtures/" + relativePath;
        try (InputStream in = ConformanceTest.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IOException("Fixture not found on classpath: " + resource);
            }
            return MAPPER.readTree(in);
        }
    }

    @TestFactory
    List<DynamicTest> verifyPasswordConformance() throws IOException {
        JsonNode fixture = loadFixture("identity/argon2id.json");
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                String phcHash = t.get("input").get("phc_hash").asText();
                String candidate = t.get("input").get("candidate_password").asText();
                boolean expected = t.get("expected").get("result").asBoolean();
                assertEquals(expected, PasswordHashing.verify(phcHash, candidate));
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> totpRfc6238Conformance() throws IOException {
        JsonNode fixture = loadFixture("identity/mfa/totp-rfc6238.json");
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                JsonNode input = t.get("input");
                byte[] secret = input.get("secret_ascii").asText().getBytes(StandardCharsets.US_ASCII);
                long timestamp = input.get("timestamp").asLong();
                int digits = input.get("digits").asInt();
                String algorithm = input.get("algorithm").asText();
                String expected = t.get("expected").get("result").asText();
                assertEquals(expected, Totp.compute(secret, timestamp, Totp.DEFAULT_PERIOD, digits, algorithm));
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> recoveryCodeFormatConformance() throws IOException {
        JsonNode fixture = loadFixture("identity/mfa/recovery-code-format.json");
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                String code = t.get("input").get("code").asText();
                boolean expected = t.get("expected").get("result").asBoolean();
                assertEquals(expected, RecoveryCodes.isValid(code));
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> webauthnAssertionConformance() throws IOException {
        return webauthnFactory("identity/mfa/webauthn-assertion.json");
    }

    @TestFactory
    List<DynamicTest> webauthnCounterConformance() throws IOException {
        return webauthnFactory("identity/mfa/webauthn-counter-decrease-rejected.json");
    }

    @TestFactory
    List<DynamicTest> webauthnAlgorithmsConformance() throws IOException {
        return webauthnFactory("identity/mfa/webauthn-assertion-algorithms.json");
    }

    private List<DynamicTest> webauthnFactory(String relativePath) throws IOException {
        JsonNode fixture = loadFixture(relativePath);
        JsonNode shared = fixture.has("shared") ? fixture.get("shared") : MAPPER.createObjectNode();
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                Map<String, Object> actual = runWebauthnFixture(shared, t.get("input"));
                Map<String, Object> expected = jsonObjectToMap(t.get("expected").get("result"));
                assertEquals(expected, actual);
            }));
        }
        return tests;
    }

    private static Map<String, Object> runWebauthnFixture(JsonNode shared, JsonNode input) {
        // Merge shared + input.
        Map<String, JsonNode> merged = new LinkedHashMap<>();
        shared.fields().forEachRemaining(e -> merged.put(e.getKey(), e.getValue()));
        input.fields().forEachRemaining(e -> merged.put(e.getKey(), e.getValue()));
        HexFormat hex = HexFormat.of();
        try {
            WebAuthnAssertionResult result = WebAuthn.verifyAssertion(
                    hex.parseHex(merged.get("cose_public_key_hex").asText()),
                    merged.get("stored_sign_count").asLong(),
                    merged.get("stored_rp_id").asText(),
                    hex.parseHex(merged.get("expected_challenge_hex").asText()),
                    merged.get("expected_origin").asText(),
                    hex.parseHex(merged.get("authenticator_data_hex").asText()),
                    hex.parseHex(merged.get("client_data_json_hex").asText()),
                    hex.parseHex(merged.get("signature_hex").asText()),
                    !merged.containsKey("require_user_verified") || merged.get("require_user_verified").asBoolean(),
                    !merged.containsKey("require_user_present") || merged.get("require_user_present").asBoolean()
            );
            Map<String, Object> out = new LinkedHashMap<>();
            out.put("ok", true);
            out.put("new_sign_count", (int) result.newSignCount());
            return out;
        } catch (WebAuthnError exc) {
            Map<String, Object> out = new LinkedHashMap<>();
            out.put("ok", false);
            out.put("reason", exc.getReason());
            return out;
        }
    }

    private static Map<String, Object> jsonObjectToMap(JsonNode obj) {
        Map<String, Object> out = new LinkedHashMap<>();
        obj.fields().forEachRemaining(e -> {
            JsonNode v = e.getValue();
            if (v.isBoolean()) {
                out.put(e.getKey(), v.asBoolean());
            } else if (v.isInt() || v.isLong()) {
                out.put(e.getKey(), v.asInt());
            } else {
                out.put(e.getKey(), v.asText());
            }
        });
        return out;
    }
}
