// Copyright 2026 NDC Digital, LLC
// SPDX-License-Identifier: Apache-2.0

package dev.flametrench.identity;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;
import java.util.HashMap;

/**
 * Flametrench v0.1 conformance suite — Java / JUnit 5 harness for the
 * identity capability.
 *
 * <p>Exercises verify_password against the cross-language Argon2id
 * parity fixture vendored from
 * github.com/flametrench/spec/conformance/fixtures/identity/.
 *
 * <p>Why this fixture matters: the fixture's PHC hash was generated by
 * the Node {@code argon2} package. Java's {@code argon2-jvm} (which
 * wraps libargon2) MUST accept it. If this test fails, password-based
 * auth has become non-portable across SDKs — a regression Flametrench
 * exists to prevent.
 */
class ConformanceTest {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private static JsonNode loadFixture(String relativePath) throws IOException {
        String resource = "/conformance/fixtures/" + relativePath;
        try (InputStream in = ConformanceTest.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IOException("Fixture not found on classpath: " + resource);
            }
            return MAPPER.readTree(in);
        }
    }

    @TestFactory
    List<DynamicTest> verifyPasswordConformance() throws IOException {
        JsonNode fixture = loadFixture("identity/argon2id.json");
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                String phcHash = t.get("input").get("phc_hash").asText();
                String candidate = t.get("input").get("candidate_password").asText();
                boolean expected = t.get("expected").get("result").asBoolean();
                assertEquals(expected, PasswordHashing.verify(phcHash, candidate));
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> totpRfc6238Conformance() throws IOException {
        JsonNode fixture = loadFixture("identity/mfa/totp-rfc6238.json");
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                JsonNode input = t.get("input");
                byte[] secret = input.get("secret_ascii").asText().getBytes(StandardCharsets.US_ASCII);
                long timestamp = input.get("timestamp").asLong();
                int digits = input.get("digits").asInt();
                String algorithm = input.get("algorithm").asText();
                String expected = t.get("expected").get("result").asText();
                assertEquals(expected, Totp.compute(secret, timestamp, Totp.DEFAULT_PERIOD, digits, algorithm));
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> recoveryCodeFormatConformance() throws IOException {
        JsonNode fixture = loadFixture("identity/mfa/recovery-code-format.json");
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                String code = t.get("input").get("code").asText();
                boolean expected = t.get("expected").get("result").asBoolean();
                assertEquals(expected, RecoveryCodes.isValid(code));
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> webauthnAssertionConformance() throws IOException {
        return webauthnFactory("identity/mfa/webauthn-assertion.json");
    }

    @TestFactory
    List<DynamicTest> webauthnCounterConformance() throws IOException {
        return webauthnFactory("identity/mfa/webauthn-counter-decrease-rejected.json");
    }

    @TestFactory
    List<DynamicTest> webauthnAlgorithmsConformance() throws IOException {
        return webauthnFactory("identity/mfa/webauthn-assertion-algorithms.json");
    }

    private List<DynamicTest> webauthnFactory(String relativePath) throws IOException {
        JsonNode fixture = loadFixture(relativePath);
        JsonNode shared = fixture.has("shared") ? fixture.get("shared") : MAPPER.createObjectNode();
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                Map<String, Object> actual = runWebauthnFixture(shared, t.get("input"));
                Map<String, Object> expected = jsonObjectToMap(t.get("expected").get("result"));
                assertEquals(expected, actual);
            }));
        }
        return tests;
    }

    private static Map<String, Object> runWebauthnFixture(JsonNode shared, JsonNode input) {
        // Merge shared + input.
        Map<String, JsonNode> merged = new LinkedHashMap<>();
        shared.fields().forEachRemaining(e -> merged.put(e.getKey(), e.getValue()));
        input.fields().forEachRemaining(e -> merged.put(e.getKey(), e.getValue()));
        HexFormat hex = HexFormat.of();
        try {
            WebAuthnAssertionResult result = WebAuthn.verifyAssertion(
                    hex.parseHex(merged.get("cose_public_key_hex").asText()),
                    merged.get("stored_sign_count").asLong(),
                    merged.get("stored_rp_id").asText(),
                    hex.parseHex(merged.get("expected_challenge_hex").asText()),
                    merged.get("expected_origin").asText(),
                    hex.parseHex(merged.get("authenticator_data_hex").asText()),
                    hex.parseHex(merged.get("client_data_json_hex").asText()),
                    hex.parseHex(merged.get("signature_hex").asText()),
                    !merged.containsKey("require_user_verified") || merged.get("require_user_verified").asBoolean(),
                    !merged.containsKey("require_user_present") || merged.get("require_user_present").asBoolean()
            );
            Map<String, Object> out = new LinkedHashMap<>();
            out.put("ok", true);
            out.put("new_sign_count", (int) result.newSignCount());
            return out;
        } catch (WebAuthnError exc) {
            Map<String, Object> out = new LinkedHashMap<>();
            out.put("ok", false);
            out.put("reason", exc.getReason());
            return out;
        }
    }

    private static Map<String, Object> jsonObjectToMap(JsonNode obj) {
        Map<String, Object> out = new LinkedHashMap<>();
        obj.fields().forEachRemaining(e -> {
            JsonNode v = e.getValue();
            if (v.isBoolean()) {
                out.put(e.getKey(), v.asBoolean());
            } else if (v.isInt() || v.isLong()) {
                out.put(e.getKey(), v.asInt());
            } else {
                out.put(e.getKey(), v.asText());
            }
        });
        return out;
    }

    // ─── v0.3: PAT conformance ───

    @TestFactory
    List<DynamicTest> patBearerPrefixRoutingConformance() throws IOException {
        JsonNode fixture = loadFixture("identity/pat/bearer-prefix-routing.json");
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                String token = t.get("input").get("token").asText();
                String expected = t.get("expected").get("result").asText();
                assertEquals(expected, AuthKind.classifyBearer(token));
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> patTokenFormatConformance() throws IOException {
        JsonNode fixture = loadFixture("identity/pat/token-format.json");
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                String token = t.get("input").get("token").asText();
                boolean expected = t.get("expected").get("result").asBoolean();
                assertEquals(expected, AuthKind.isStructurallyValidPatToken(token));
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> patStructuralFormatOnlyConformance() throws IOException {
        JsonNode fixture = loadFixture("identity/pat/structural-format-only.json");
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                String token = t.get("input").get("token").asText();
                boolean expected = t.get("expected").get("result").asBoolean();
                assertEquals(expected, AuthKind.isStructurallyValidPatToken(token));
            }));
        }
        return tests;
    }

    // ─── v0.2: list-users / user-display-name conformance (ADR 0015 / ADR 0014) ───

    @TestFactory
    List<DynamicTest> listUsersConformance() throws IOException {
        return runStepFixture("identity/list-users.json");
    }

    @TestFactory
    List<DynamicTest> userDisplayNameConformance() throws IOException {
        return runStepFixture("identity/user-display-name.json");
    }

    // ─── Step-DSL interpreter for fixtures with operation sequences ───

    private List<DynamicTest> runStepFixture(String fixturePath) throws IOException {
        JsonNode fixture = loadFixture(fixturePath);
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                InMemoryIdentityStore store = new InMemoryIdentityStore();
                Map<String, String> vars = new HashMap<>();
                for (JsonNode step : t.get("steps")) {
                    executeStep(store, step, vars);
                }
            }));
        }
        return tests;
    }

    private void executeStep(
            InMemoryIdentityStore store, JsonNode step, Map<String, String> vars
    ) {
        String op = step.get("op").asText();
        JsonNode inp = step.has("input") ? step.get("input") : MAPPER.createObjectNode();
        JsonNode caps = step.has("captures") ? step.get("captures") : null;
        JsonNode exp = step.has("expected") ? step.get("expected") : null;

        switch (op) {
            case "create_user" -> {
                String dn = inp.has("display_name") && !inp.get("display_name").isNull()
                        ? inp.get("display_name").asText() : null;
                User user = dn != null ? store.createUser(dn) : store.createUser();
                capture(caps, vars, "user.id", user.id());
            }
            case "create_user_with_password_credential" -> {
                String identifier = inp.get("identifier").asText();
                String password = inp.get("password").asText();
                User user = store.createUser();
                PasswordCredential cred = store.createPasswordCredential(
                        user.id(), identifier, password);
                capture(caps, vars, "user.id", user.id());
                capture(caps, vars, "credential.id", cred.id());
            }
            case "suspend_user" ->
                store.suspendUser(resolveVars(inp.get("usr_id").asText(), vars));
            case "revoke_user" ->
                store.revokeUser(resolveVars(inp.get("usr_id").asText(), vars));
            case "revoke_credential" ->
                store.revokeCredential(resolveVars(inp.get("cred_id").asText(), vars));
            case "list_users" -> {
                String cursor = inp.has("cursor")
                        ? resolveVars(inp.get("cursor").asText(), vars) : null;
                int limit = inp.has("limit") ? inp.get("limit").asInt() : 200;
                String query = inp.has("query") ? inp.get("query").asText() : null;
                Status status = inp.has("status") ? parseStatus(inp.get("status").asText()) : null;
                Page<User> page = store.listUsers(cursor, limit, query, status);
                capture(caps, vars, "page.next_cursor", page.nextCursor());
                if (exp != null && exp.has("result")) {
                    assertPageResult(page, exp.get("result"), vars);
                }
            }
            case "update_user" -> {
                String usrId = resolveVars(inp.get("usr_id").asText(), vars);
                final String dn;
                if (inp.has("display_name")) {
                    dn = inp.get("display_name").isNull() ? null : inp.get("display_name").asText();
                } else {
                    dn = IdentityStore.UNSET;
                }
                if (exp != null && exp.has("error")) {
                    Class<? extends RuntimeException> err =
                            stepErrorClass(exp.get("error").asText());
                    assertThrows(err, () -> store.updateUser(usrId, dn));
                } else {
                    store.updateUser(usrId, dn);
                }
            }
            case "assert_user_fields" -> {
                String usrId = resolveVars(inp.get("usr_id").asText(), vars);
                User user = store.getUser(usrId);
                if (inp.has("expected_display_name")) {
                    if (inp.get("expected_display_name").isNull()) {
                        assertNull(user.displayName());
                    } else {
                        assertEquals(inp.get("expected_display_name").asText(), user.displayName());
                    }
                }
            }
            default -> throw new IllegalArgumentException("Unknown step op: " + op);
        }
    }

    private void assertPageResult(Page<User> page, JsonNode result, Map<String, String> vars) {
        if (result.has("data_ids_in_order")) {
            List<String> expected = new ArrayList<>();
            result.get("data_ids_in_order").forEach(n -> expected.add(resolveVars(n.asText(), vars)));
            List<String> actual = page.data().stream().map(User::id).toList();
            assertEquals(expected, actual, "data_ids_in_order");
        }
        if (result.has("data_ids_unordered")) {
            List<String> expected = new ArrayList<>();
            result.get("data_ids_unordered").forEach(
                    n -> expected.add(resolveVars(n.asText(), vars)));
            List<String> actual = page.data().stream().map(User::id).toList();
            assertEquals(
                    new java.util.HashSet<>(expected),
                    new java.util.HashSet<>(actual),
                    "data_ids_unordered");
        }
        if (result.has("next_cursor")) {
            if (result.get("next_cursor").isNull()) {
                assertNull(page.nextCursor(), "next_cursor");
            } else {
                assertEquals(
                        resolveVars(result.get("next_cursor").asText(), vars),
                        page.nextCursor(), "next_cursor");
            }
        }
        if (result.has("user_display_names")) {
            java.util.Map<String, User> byId = new java.util.HashMap<>();
            page.data().forEach(u -> byId.put(u.id(), u));
            result.get("user_display_names").fields().forEachRemaining(e -> {
                String uid = resolveVars(e.getKey(), vars);
                User u = byId.get(uid);
                assertNotNull(u, "user " + uid + " not in page");
                if (e.getValue().isNull()) {
                    assertNull(u.displayName(), "displayName for " + uid);
                } else {
                    assertEquals(e.getValue().asText(), u.displayName(), "displayName for " + uid);
                }
            });
        }
    }

    private static void capture(
            JsonNode caps, Map<String, String> vars, String path, String value
    ) {
        if (caps == null) return;
        caps.fields().forEachRemaining(e -> {
            if (path.equals(e.getValue().asText())) vars.put(e.getKey(), value);
        });
    }

    private static String resolveVars(String s, Map<String, String> vars) {
        if (s == null || !s.contains("{")) return s;
        StringBuilder sb = new StringBuilder();
        int i = 0;
        while (i < s.length()) {
            int open = s.indexOf('{', i);
            if (open < 0) { sb.append(s, i, s.length()); break; }
            sb.append(s, i, open);
            int close = s.indexOf('}', open + 1);
            if (close < 0) { sb.append(s, open, s.length()); break; }
            sb.append(vars.getOrDefault(s.substring(open + 1, close), s.substring(open, close + 1)));
            i = close + 1;
        }
        return sb.toString();
    }

    private static Status parseStatus(String s) {
        return switch (s) {
            case "active"    -> Status.ACTIVE;
            case "suspended" -> Status.SUSPENDED;
            case "revoked"   -> Status.REVOKED;
            default          -> null;
        };
    }

    private static Class<? extends RuntimeException> stepErrorClass(String name) {
        return switch (name) {
            case "AlreadyTerminalError" -> AlreadyTerminalError.class;
            case "NotFoundError"        -> NotFoundError.class;
            default -> throw new IllegalArgumentException("Unknown step error: " + name);
        };
    }
}
