// Copyright 2026 NDC Digital, LLC
// SPDX-License-Identifier: Apache-2.0

package dev.flametrench.identity;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Flametrench v0.1 conformance suite — Java / JUnit 5 harness for the
 * identity capability.
 *
 * <p>Exercises verify_password against the cross-language Argon2id
 * parity fixture vendored from
 * github.com/flametrench/spec/conformance/fixtures/identity/.
 *
 * <p>Why this fixture matters: the fixture's PHC hash was generated by
 * the Node {@code argon2} package. Java's {@code argon2-jvm} (which
 * wraps libargon2) MUST accept it. If this test fails, password-based
 * auth has become non-portable across SDKs — a regression Flametrench
 * exists to prevent.
 */
class ConformanceTest {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private static JsonNode loadFixture(String relativePath) throws IOException {
        String resource = "/conformance/fixtures/" + relativePath;
        try (InputStream in = ConformanceTest.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IOException("Fixture not found on classpath: " + resource);
            }
            return MAPPER.readTree(in);
        }
    }

    @TestFactory
    List<DynamicTest> verifyPasswordConformance() throws IOException {
        JsonNode fixture = loadFixture("identity/argon2id.json");
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode t : fixture.get("tests")) {
            String id = t.get("id").asText();
            String desc = t.get("description").asText();
            tests.add(DynamicTest.dynamicTest("[" + id + "] " + desc, () -> {
                String phcHash = t.get("input").get("phc_hash").asText();
                String candidate = t.get("input").get("candidate_password").asText();
                boolean expected = t.get("expected").get("result").asBoolean();
                assertEquals(expected, PasswordHashing.verify(phcHash, candidate));
            }));
        }
        return tests;
    }
}
